// #r @"C:\dev\code\graphplat\packages\fsi\NETStandard.Library.NETFramework\build\net461\lib\netstandard.dll"
// #r @"C:\Users\Gregor\.nuget\packages\aether\8.2.0\lib\net45\Aether.dll"
#r @"C:\Users\Gregor\.nuget\packages\baseline\1.5.0\lib\net46\Baseline.dll"
#r @"C:\Users\Gregor\.nuget\packages\marten.fsharp\0.1.1\lib\net46\Marten.FSharp.dll"
#r @"C:\Users\Gregor\.nuget\packages\system.threading.tasks.extensions\4.4.0\lib\netstandard2.0\System.Threading.Tasks.Extensions.dll"
#r @"C:\Users\Gregor\.nuget\packages\marten\2.7.1\lib\net46\Marten.dll"
#r @"C:\Users\Gregor\.nuget\packages\newtonsoft.json\11.0.2\lib\net45\Newtonsoft.Json.dll"
#r @"C:\Users\Gregor\.nuget\packages\npgsql\3.2.5\lib\net451\Npgsql.dll"
#r @"C:\Users\Gregor\.nuget\packages\remotion.linq\2.2.0\lib\net45\Remotion.Linq.dll"
// #load @"c:\dev\code\graphplat\src\Shared\Shared.fs"
// #load @"c:\dev\code\graphplat\src\Server\Server.fs"
